# Site/MainBundle/Resources/config/admin.yml
services:
    sonata.admin.menu:
        class: Site\MainBundle\Admin\MenuAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Menu" }
        arguments:
            - ~
            - Site\MainBundle\Entity\Menu
            - ~
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.gallery:
        class: Site\MainBundle\Admin\GalleryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Catalogs" }
        arguments:
            - ~
            - Site\MainBundle\Entity\Gallery
            - 'SiteMainBundle:GalleryAdmin'
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.image:
        class: Site\MainBundle\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Gallery" }
        arguments:
            - ~
            - Site\MainBundle\Entity\Image
            - 'SiteMainBundle:ImageAdmin'
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.slider:
        class: Site\MainBundle\Admin\SliderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Slider" }
        arguments:
            - ~
            - Site\MainBundle\Entity\Slider
            - ~
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.video:
        class: Site\MainBundle\Admin\VideoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Video" }
        arguments:
            - ~
            - Site\MainBundle\Entity\Video
            - ~
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.bottomImage:
        class: Site\MainBundle\Admin\BottomImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Lower picture" }
        arguments:
            - ~
            - Site\MainBundle\Entity\BottomImage
            - ~
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.map:
        class: Site\MainBundle\Admin\MapAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Map" }
        arguments:
            - ~
            - Site\MainBundle\Entity\Map
            - ~
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.catalogs:
        class: Site\MainBundle\Admin\CatalogsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Catalogs" }
        arguments:
            - ~
            - Site\MainBundle\Entity\Catalogs
            - ~
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.newsGallery:
        class: Site\MainBundle\Admin\NewsGalleryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "News" }
        arguments:
            - ~
            - Site\MainBundle\Entity\NewsGallery
            - 'SiteMainBundle:NewsGalleryAdmin'
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.newsGalleryIt:
        class: Site\MainBundle\Admin\NewsGalleryItAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "NewsIt" }
        arguments:
            - ~
            - Site\MainBundle\Entity\NewsGalleryIt
            - 'SiteMainBundle:NewsGalleryItAdmin'
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.newsGalleryRu:
        class: Site\MainBundle\Admin\NewsGalleryRuAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "NewsRu" }
        arguments:
            - ~
            - Site\MainBundle\Entity\NewsGalleryRu
            - 'SiteMainBundle:NewsGalleryRuAdmin'
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.newsGalleryCn:
        class: Site\MainBundle\Admin\NewsGalleryCnAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "NewsRu" }
        arguments:
            - ~
            - Site\MainBundle\Entity\NewsGalleryCn
            - 'SiteMainBundle:NewsGalleryCnAdmin'
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.feedbackCatalog:
        class: Site\MainBundle\Admin\FeedbackCatalogAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "FeedbackCatalog" }
        arguments:
            - ~
            - Site\MainBundle\Entity\FeedbackCatalog
            - ~
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.client:
        class: Site\MainBundle\Admin\ClientAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Clients" }
        arguments:
            - ~
            - Site\MainBundle\Entity\Client
            - 'SiteMainBundle:ClientAdmin'
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.zone:
        class: Site\MainBundle\Admin\ZoneCatalogsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Zone" }
        arguments:
            - ~
            - Site\MainBundle\Entity\ZoneCatalogs
            - ~
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.colorGroup:
        class: Site\MainBundle\Admin\ColorGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Color Group" }
        arguments:
            - ~
            - Site\MainBundle\Entity\ColorGroup
            - ~
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]
    sonata.admin.color:
        class: Site\MainBundle\Admin\ColorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Color" }
        arguments:
            - ~
            - Site\MainBundle\Entity\Color
            - ~
        calls:
            - [ setTranslationDomain, [SiteMainBundle]]