parameters:
#    Site_main.example.class: Site\MainBundle\Example

services:
#    Site_main.example:
#        class: %Site_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    site.twig.site_extension:
        class: Site\MainBundle\Twig\SiteExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
