security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        site_mainbundle:
            entity:
                class: SiteMainBundle:Client
                property: username
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
        Application\Sonata\UserBundle\Entity\User:
            sha512
        Site\MainBundle\Entity\Client:
            sha512
        Symfony\Component\Security\Core\User\User:
            plaintext

    firewalls:
        admin:
            pattern:            /admin(.*)
            context:            user
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
            anonymous:          true

        default:
            pattern:    ^/
            anonymous: true
            form_login:
                login_path:  /client/login
                check_path:  /client/login_check
                always_use_default_target_path: true
                remember_me: true
            logout:
                path: /client/logout
            anonymous:  true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/client/catalogs, role: [ROLE_USER] }

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        # [...]
    acl:
        connection: default
