<?php

namespace Site\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ZoneCatalogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogsRepository extends EntityRepository
{
    public function findBySlugZone($slug){
        if(!is_null($slug)){
            $em = $this->getEntityManager();
            $query = $em->createQuery("
                SELECT c FROM SiteMainBundle:Catalogs c
                LEFT JOIN c.zone z
                WHERE z.slug = :slug
                ORDER BY c.position ASC
            ")
            ->setParameters(array(
                'slug' => $slug
            ));

            $catalogs = $query->getResult();

            return $catalogs;
        }
        return false;
    }

    public function findCatalogs(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("
            SELECT c FROM SiteMainBundle:Catalogs c
            WHERE c.type = 0
            ORDER BY c.position ASC
        ");

        $catalogs = $query->getResult();

        return $catalogs;
    }
}
